### PR TITLE
Create cmake-multi-platform.yml

### PR DESCRIPTION
**Pull request by berry369**

### CODE REVIEW

**Comment by berry369** [comment]
WOW //. I just don't get it

**Comment by berry369** [comment]
Okay

**Comment by berry369** [comment]
[3aeebbdd359005c948e2342b0bcaadff7d57.pdf](https://github.com/user-attachments/files/16898205/3aeebbdd359005c948e2342b0bcaadff7d57.pdf)

I know I am going to mess this up .WHAT IS THIS

**Comment by evoskuil** [comment]
Spam

**Pull request closed without merging**
