### PR TITLE
end_write() must return true unless flush() fails

### PR DESCRIPTION
**Pull request by JasonCoombs**
my debugging indicates there is a condition in which another thread has deleted the flush_lock file already when end_write() is called, but that's not an error condition and should not cause callers to conclude that an error::store_lock_failure has occurred. all is well with the tables at this point and the only reason we have just tried to delete a non-existent file is that we are treating the flush locking mechanism as idempotent. Multiple calls to create the flush_lock file are not an error condition, either. if boost::filesystem::remove() does encounter an error, it won't signal that with a FALSE return value in any case because boost throws exceptions for that. see:

https://www.boost.org/doc/libs/1_46_1/libs/filesystem/v3/doc/reference.html#remove

### CODE REVIEW

**Comment by JasonCoombs** [comment]
I think there is still a potential problem with flush_lock::lock_shared called by begin_write() here:

https://github.com/libbitcoin/libbitcoin-database/blob/master/src/store.cpp#L122

we're creating a new std::ofstream instance and opening the underlying lock file in write mode. this is not protected by mutex or other critical section mechanism, so more than one thread may create new instances of std::ofstream referencing the same lock file simultaneously in the event that locked_ has not yet been set to true during a preempted call to create().

https://github.com/libbitcoin/libbitcoin/blob/master/src/utility/flush_lock.cpp#L67

See also:
http://www.cplusplus.com/reference/fstream/ofstream/ofstream/

**Comment by evoskuil** [comment]
The `flush_lock` class is not thread safe, its caller must guard it. Flushing after individual writes is not feasible with concurrent writes, which is why `bc::database::data_base` conditionally serializes writes when write flushing is enabled.

**Comment by JasonCoombs** [comment]
According to the comments, here:

https://github.com/libbitcoin/libbitcoin/blob/master/src/utility/flush_lock.cpp#L61

flush_lock was meant to have idempotency for lock_shared and unlock_shared

Where (in v3 or in v4) were these lock and unlock calls being serialized? I'm confused.

**Comment by evoskuil** [comment]
Look for critical section comments in data_base. It is idempotent, but not thread safe.

**Comment by JasonCoombs** [comment]
The following will need to be added to this PR if it's going to be accepted. There are related changes necessary in data_base.cpp and conditional_lock.cpp so I'm finishing testing and will submit new PRs

in flush_lock.cpp:

```
bool flush_lock::unlock_shared()
{
    if (!locked_)
        return true;

    bool retval = destroy(file_);

    // always set locked_ to false, even if boost::filesystem::remove() returns false
    locked_ = false;

    // a return value of false is not an error, it's useful for debugging purposes only
    // false indicates that the flush lock file was already deleted when remove() was called
    return retval;
}
```

**Comment by JasonCoombs** [comment]
Correction to the last comment: it's possible that with the changes to conditional_lock.cpp that we WILL want to treat a FALSE return value from boost::filesystem::remove() to be a fatal error. My testing suggests that we may be able to rely on flush lock file creation / destruction as originally expected, as long as the conditional_lock is functional. The problem here may have been that conditional_lock was not working, so I'm still considering whether it makes any sense to presume the store to be corrupted based only on a "missing" flush lock file when we attempt to remove it. TBD

**Comment by evoskuil** [comment]
This identifies an actual problem but is not a correct fix for that problem. The flush lock must be made file-specific because each file must be locked and flushed independently during a parallel write. The problem is that writes are locked per file but the flush lock spans files.

https://github.com/libbitcoin/libbitcoin-database/issues/232

**Pull request closed without merging**
